spring.application.name=cryptoclicker

#spring.application.name=demo

spring.datasource.username=Aries
spring.datasource.password=

# use in-memory database
spring.datasource.url=jdbc:h2:file:./CryptoDB

# use file-based database
#spring.datasource.url=jdbc:h2:file:./testdb

# recreate the database schema on startup and drop it on shutdown
#spring.jpa.hibernate.ddl-auto=create-drop

# update the database schema on startup without dropping it on shutdown
spring.jpa.hibernate.ddl-auto=update

# defer running data.sql until tables are created
spring.jpa.defer-datasource-initialization=true

# Always run data.sql, even for file-based database or MySQL
#spring.sql.init.mode=always

# enable H2 console for debugging purposes
spring.h2.console.enabled=true

server.port=8080

server.servlet.session.timeout = 30m